### ISSUE TITLE
pupil-1.1 not starting on ubuntu 17.10

### ISSUE THREAD

**Issue by callummole** [pupil-labs/pupil#929]
Hi, 

I've recently downloaded pupil-labs v1.1, but am having trouble starting it. It may have something to do with me recently updating ubuntu to 17.10, but I'm not certain (I'm relatively new to linux).

When you run from source you get:
eyetrike@eyetrike-ThinkPad-E570:~/pupil-1.1/pupil_src$ python3 main.pyError calling git: "Command '['git', 'describe', '--tags']' returned non-zero exit status 128." 
 output: "b'fatal: Not a git repository (or any of the parent directories): .git\n'"
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    app_version = get_version(version_file)
  File "/home/eyetrike/pupil-1.1/pupil_src/shared_modules/version_utils.py", line 69, in get_version
    version = pupil_version()
  File "/home/eyetrike/pupil-1.1/pupil_src/shared_modules/version_utils.py", line 51, in pupil_version
    version = get_tag_commit().decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'

When you run the app you get: 
eyetrike@eyetrike-ThinkPad-E570:~$ pupil_capture
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables/world.py", line 98, in world
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller-3.3.dev0+g8998a9d-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2

world - [INFO] launchables.world: Process shutting down.

Any help appreciated.

**Comment by mkassner** [comment]
Hi,

when trying to run from source please do the following:
git clone the repository.  Just downloading the source files breaks our version scripts. 

Can you try the bundle from here:
https://drive.google.com/open?id=1KeAgmosLyn8kZ_xTJy_lVom5NNyXxG69

and let me know if if works on 17.10?

**Comment by callummole** [comment]
Tried the bundle, unfortunately still get the same error as above.

**Comment by callummole** [comment]
However, when I run pupil-capture from source (after cloning), it runs fine.

**Comment by mkassner** [comment]
Hi, sorry i uploaded the wrong bundle! Please try again:

https://drive.google.com/open?id=1lxtevzD1szstHjsXW99LtOBNLRwEhCc6
Thank you!

**Comment by callummole** [comment]
The new bundle works on 17.10 fine.

Thanks!

**Comment by mkassner** [comment]
Awesome! I will update all bundles.

**Comment by callummole** [comment]
Hi, the pupil player and pupil service also struggle to work on ubuntu 17.10. Apologies for not trying these out when I reported the previous issue. Presumably they are related.

If you try and run pupil player you get:

eyetrike@eyetrike-ThinkPad-E570:~$ pupil_player
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [ERROR] launchables.player: Process player_drop crashed with trace:
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 144, in __init__
  File "ctypes/__init__.py", line 344, in __init__
OSError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OpenGL/platform/glx.py", line 17, in GL
  File "OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 146, in __init__
PyInstallerImportError: ("Failed to load dynlib/dll 'libGL.so.1'. Most probably this dynlib/dll was not found when the application was frozen.", 'libGL.so.1', 'libGL.so.1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launchables/player.py", line 534, in player_drop
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller-3.3.dev0+g8998a9d-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "shared_modules/gl_utils/__init__.py", line 12, in <module>
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller-3.3.dev0+g8998a9d-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "shared_modules/gl_utils/utils.py", line 15, in <module>
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller-3.3.dev0+g8998a9d-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "OpenGL/GL/__init__.py", line 3, in <module>
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller-3.3.dev0+g8998a9d-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "OpenGL/error.py", line 12, in <module>
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller-3.3.dev0+g8998a9d-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "OpenGL/platform/__init__.py", line 35, in <module>
  File "OpenGL/platform/__init__.py", line 32, in _load
  File "OpenGL/platform/baseplatform.py", line 92, in install
  File "OpenGL/platform/baseplatform.py", line 14, in __get__
  File "OpenGL/platform/glx.py", line 96, in GetCurrentContext
  File "OpenGL/platform/baseplatform.py", line 14, in __get__
  File "OpenGL/platform/glx.py", line 20, in GL
ImportError: ('Unable to load OpenGL library', "Failed to load dynlib/dll 'libGL.so.1'. Most probably this dynlib/dll was not found when the application was frozen.", 'libGL.so.1', 'libGL.so.1')


and if you try and run pupil service you get:

### eyetrike@eyetrike-ThinkPad-E570:~$ pupil_service
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
service - [ERROR] launchables.service: Process Service crashed with trace:
Traceback (most recent call last):
  File "launchables/service.py", line 88, in service
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller-3.3.dev0+g8998a9d-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "shared_modules/pupil_detectors/__init__.py", line 18, in <module>
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller-3.3.dev0+g8998a9d-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
  File "pupil_detectors/detector_2d.pyx", line 17, in init pupil_detectors.detector_2d (detector_2d.cpp:26699)
  File "/home/pupil-labs/.pyenv/versions/3.6.0/envs/general/lib/python3.6/site-packages/PyInstaller-3.3.dev0+g8998a9d-py3.6.egg/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2

service - [INFO] launchables.service: Process shutting down.

**Comment by mkassner** [comment]
@callummole  please try the latest bundles. I just uploaded the version with 17.10 fixes. https://github.com/pupil-labs/pupil/releases/tag/v1.1

**Comment by callummole** [comment]
New bundles start fine. Thanks again.

**Comment by mkassner** [comment]
@callummole  Can you confirm that the cameras are working for you? We have some users on 17.10 that have trouble...

**Comment by callummole** [comment]
@mkassner it was working very well until I accepted some recommended linux updates. See issue #954

**Comment by mkassner** [comment]
ok. We have a fix for this. (It is actually a linux kernel bug.) I ll upload the fixed bundle on Monday.
