### ISSUE TITLE
3D Eye Model: build on Ubuntu 14.04

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#274]
While all dependencies can be build easily:

```shell
sudo apt-get install cmake
sudo apt-get install libgoogle-glog-dev
sudo apt-get install libatlas-base-dev
sudo apt-get install libeigen3-dev
sudo add-apt-repository ppa:bzindovic/suitesparse-bugfix-1319687
sudo apt-get update
sudo apt-get install libsuitesparse-dev
```

now download ceres from here:
```shell
tar zxf ceres-solver-1.11.0.tar.gz
cd ceres
mkdir build && cd build
cmake ..
make -j3
make test
sudo make install
```

I cant get our cython extensions (2d and 3d) to build. I tried gcc and clang both throw (different) errors during building off the cpp source.

An excerpt below:

```shell
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/usr/include/python2.7 -c detector_2d.cpp -o build/temp.linux-x86_64-2.7/detector_2d.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
detector_2d.cpp: In function ‘PyObject* __pyx_pf_15pupil_detectors_11detector_2d_11Detector_2D_8detect(__pyx_obj_15pupil_detectors_11detector_2d_Detector_2D*, PyObject*, PyObject*, PyObject*, PyObject*)’:
detector_2d.cpp:2636:3: error: ‘cv::Mat::Mat’ names the constructor, not the type
   cv::Mat::Mat __pyx_v_frame;
   ^
detector_2d.cpp:2636:16: error: expected ‘;’ before ‘__pyx_v_frame’
   cv::Mat::Mat __pyx_v_frame;
                ^
detector_2d.cpp:2636:29: error: statement cannot resolve address of overloaded function
   cv::Mat::Mat __pyx_v_frame;
                             ^
detector_2d.cpp:2638:3: error: ‘cv::Mat::Mat’ names the constructor, not the type
   cv::Mat::Mat __pyx_v_frameColor;
   ^
detector_2d.cpp:2638:16: error: expected ‘;’ before ‘__pyx_v_frameColor’
   cv::Mat::Mat __pyx_v_frameColor;
                ^
detector_2d.cpp:2638:34: error: statement cannot resolve address of overloaded function
   cv::Mat::Mat __pyx_v_frameColor;
                                  ^
detector_2d.cpp:2639:3: error: ‘cv::Mat::Mat’ names the constructor, not the type
   cv::Mat::Mat __pyx_v_debugImage;
   ^
detector_2d.cpp:2639:16: error: expected ‘;’ before ‘__pyx_v_debugImage’
   cv::Mat::Mat __pyx_v_debugImage;
                ^
detector_2d.cpp:2639:34: error: statement cannot resolve address of overloaded function
   cv::Mat::Mat __pyx_v_debugImage;
                                  ^
detector_2d.cpp:2668:3: error: ‘cv::Mat::Mat’ names the constructor, not the type
   cv::Mat::Mat __pyx_t_8;
   ^
detector_2d.cpp:2668:16: error: expected ‘;’ before ‘__pyx_t_8’
   cv::Mat::Mat __pyx_t_8;
                ^
detector_2d.cpp:2668:25: error: statement cannot resolve address of overloaded function
   cv::Mat::Mat __pyx_t_8;
                         ^
detector_2d.cpp:2686:19: error: expected primary-expression before ‘int’
   cv::Rect::Rect_<int>  __pyx_t_26;
                   ^
detector_2d.cpp:2686:19: error: expected ‘;’ before ‘int’
detector_2d.cpp:2759:5: error: ‘__pyx_t_8’ was not declared in this scope
     __pyx_t_8 = cv::Mat::Mat(__pyx_t_3, __pyx_t_4, CV_8UC1, ((void *)(&(*((unsigned char *) ( /* dim=1 */ ((char *) (((unsigned char *) ( /* dim=0 */ (__pyx_v_img.data + __pyx_t_5 * __pyx_v_img.strides[0]) )) + __pyx_t_6)) ))))));
     ^
detector_2d.cpp:2759:229: error: cannot call constructor ‘cv::Mat::Mat’ directly [-fpermissive]
     __pyx_t_8 = cv::Mat::Mat(__pyx_t_3, __pyx_t_4, CV_8UC1, ((void *)(&(*((unsigned char *) ( /* dim=1 */ ((char *) (((unsigned char *) ( /* dim=0 */ (__pyx_v_img.data + __pyx_t_5 * __pyx_v_img.strides[0]) )) + __pyx_t_6)) ))))));
                                                                                                                                                                                                                                     ^
detector_2d.cpp:2759:229: error:   for a function-style cast, remove the redundant ‘::Mat’ [-fpermissive]
detector_2d.cpp:2764:3: error: ‘__pyx_v_frame’ was not declared in this scope
   __pyx_v_frame = __pyx_t_8;
   ^
detector_2d.cpp:2764:19: error: ‘__pyx_t_8’ was not declared in this scope
   __pyx_v_frame = __pyx_t_8;
                   ^
detector_2d.cpp:2945:307: error: cannot call constructor ‘cv::Mat::Mat’ directly [-fpermissive]
       __pyx_t_8 = cv::Mat::Mat(__pyx_t_4, __pyx_t_3, CV_8UC3, ((void *)(&(*((unsigned char *) ( /* dim=2 */ (( /* dim=1 */ (( /* dim=0 */ (__pyx_v_img_color.data + __pyx_t_15 * __pyx_v_img_color.strides[0]) ) + __pyx_t_16 * __pyx_v_img_color.strides[1]) ) + __pyx_t_17 * __pyx_v_img_color.strides[2]) ))))));
                                                                                                                                                                                                                                                                                                                   ^
detector_2d.cpp:2945:307: error:   for a function-style cast, remove the redundant ‘::Mat’ [-fpermissive]
detector_2d.cpp:2950:5: error: ‘__pyx_v_frameColor’ was not declared in this scope
     __pyx_v_frameColor = __pyx_t_8;
     ^
detector_2d.cpp:3061:335: error: cannot call constructor ‘cv::Mat::Mat’ directly [-fpermissive]
       __pyx_t_8 = cv::Mat::Mat(__pyx_t_3, __pyx_t_4, CV_8UC3, ((void *)(&(*((unsigned char *) ( /* dim=2 */ (( /* dim=1 */ (( /* dim=0 */ (__pyx_v_self->debugImage.data + __pyx_t_18 * __pyx_v_self->debugImage.strides[0]) ) + __pyx_t_19 * __pyx_v_self->debugImage.strides[1]) ) + __pyx_t_20 * __pyx_v_self->debugImage.strides[2]) ))))));
                                                                                                                                                                                                                                                                                                                                               ^
detector_2d.cpp:3061:335: error:   for a function-style cast, remove the redundant ‘::Mat’ [-fpermissive]
detector_2d.cpp:3066:5: error: ‘__pyx_v_debugImage’ was not declared in this scope
     __pyx_v_debugImage = __pyx_t_8;
     ^
detector_2d.cpp:3692:5: error: ‘__pyx_t_26’ was not declared in this scope
     __pyx_t_26 = cv::Rect::Rect_<int> (__pyx_t_3, __pyx_t_4, __pyx_t_7, __pyx_t_25);
     ^
detector_2d.cpp:3692:34: error: expected primary-expression before ‘int’
     __pyx_t_26 = cv::Rect::Rect_<int> (__pyx_t_3, __pyx_t_4, __pyx_t_7, __pyx_t_25);
                                  ^
detector_2d.cpp:3692:34: error: expected ‘;’ before ‘int’
detector_2d.cpp:3699:83: error: ‘__pyx_v_frameColor’ was not declared in this scope
   __pyx_v_cppResultPtr = __pyx_v_self->thisptr->detect(__pyx_t_24, __pyx_v_frame, __pyx_v_frameColor, __pyx_v_debugImage, __pyx_t_26, __pyx_t_9, __pyx_t_27);
                                                                                   ^
detector_2d.cpp:3699:103: error: ‘__pyx_v_debugImage’ was not declared in this scope
   __pyx_v_cppResultPtr = __pyx_v_self->thisptr->detect(__pyx_t_24, __pyx_v_frame, __pyx_v_frameColor, __pyx_v_debugImage, __pyx_t_26, __pyx_t_9, __pyx_t_27);
                                                                                                       ^
detector_2d.cpp:3699:123: error: ‘__pyx_t_26’ was not declared in this scope
   __pyx_v_cppResultPtr = __pyx_v_self->thisptr->detect(__pyx_t_24, __pyx_v_frame, __pyx_v_frameColor, __pyx_v_debugImage, __pyx_t_26, __pyx_t_9, __pyx_t_27);
                                                                                                                           ^
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /usr/local/include/opencv2/core/core.hpp:56,
                 from detector_2d.cpp:320:
/usr/include/c++/4.8/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::vector<cv::Point_<int> >*, std::vector<std::vector<cv::Point_<int> > > >; _Tp = std::vector<cv::Point_<int> >; _Compare = Detector2D::detect(singleeyefitter::Detector2DProperties&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect&, bool, bool, bool)::__lambda4]’:
/usr/include/c++/4.8/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::vector<cv::Point_<int> >*, std::vector<std::vector<cv::Point_<int> > > >; _Compare = Detector2D::detect(singleeyefitter::Detector2DProperties&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect&, bool, bool, bool)::__lambda4]’
/usr/include/c++/4.8/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::vector<cv::Point_<int> >*, std::vector<std::vector<cv::Point_<int> > > >; _Size = long int; _Compare = Detector2D::detect(singleeyefitter::Detector2DProperties&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect&, bool, bool, bool)::__lambda4]’
/usr/include/c++/4.8/bits/stl_algo.h:5499:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<std::vector<cv::Point_<int> >*, std::vector<std::vector<cv::Point_<int> > > >; _Compare = Detector2D::detect(singleeyefitter::Detector2DProperties&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect&, bool, bool, bool)::__lambda4]’
detect_2d.hpp:284:124:   required from here
/usr/include/c++/4.8/bits/stl_algo.h:2263:35: error: no match for call to ‘(Detector2D::detect(singleeyefitter::Detector2DProperties&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect&, bool, bool, bool)::__lambda4) (std::vector<cv::Point_<int> >&, const std::vector<cv::Point_<int> >&)’
    while (__comp(*__first, __pivot))
                                   ^
In file included from detector_2d.cpp:323:0:
detect_2d.hpp:284:59: note: candidates are:
  std::sort(split_contours.begin(), split_contours.end(), [](Contour_2D & a, Contour_2D & b) { return a.size() > b.size(); });
                                                           ^
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /usr/local/include/opencv2/core/core.hpp:56,
                 from detector_2d.cpp:320:
/usr/include/c++/4.8/bits/stl_algo.h:2263:35: note: bool (*)(singleeyefitter::Contour_2D&, singleeyefitter::Contour_2D&) {aka bool (*)(std::vector<cv::Point_<int> >&, std::vector<cv::Point_<int> >&)} <conversion>
    while (__comp(*__first, __pivot))
                                   ^
/usr/include/c++/4.8/bits/stl_algo.h:2263:35: note:   candidate expects 3 arguments, 3 provided
In file included from detector_2d.cpp:323:0:
detect_2d.hpp:284:91: note: Detector2D::detect(singleeyefitter::Detector2DProperties&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect&, bool, bool, bool)::__lambda4
  std::sort(split_contours.begin(), split_contours.end(), [](Contour_2D & a, Contour_2D & b) { return a.size() > b.size(); });
                                                                                           ^
detect_2d.hpp:284:91: note:   no known conversion for argument 2 from ‘const std::vector<cv::Point_<int> >’ to ‘singleeyefitter::Contour_2D& {aka std::vector<cv::Point_<int> >&}’
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /usr/local/include/opencv2/core/core.hpp:56,
                 from detector_2d.cpp:320:
/usr/include/c++/4.8/bits/stl_algo.h:2266:34: error: no match for call to ‘(Detector2D::detect(singleeyefitter::Detector2DProperties&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect&, bool, bool, bool)::__lambda4) (const std::vector<cv::Point_<int> >&, std::vector<cv::Point_<int> >&)’
    while (__comp(__pivot, *__last))
                                  ^
In file included from detector_2d.cpp:323:0:
detect_2d.hpp:284:59: note: candidates are:
  std::sort(split_contours.begin(), split_contours.end(), [](Contour_2D & a, Contour_2D & b) { return a.size() > b.size(); });
                                                           ^
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /usr/local/include/opencv2/core/core.hpp:56,
                 from detector_2d.cpp:320:
/usr/include/c++/4.8/bits/stl_algo.h:2266:34: note: bool (*)(singleeyefitter::Contour_2D&, singleeyefitter::Contour_2D&) {aka bool (*)(std::vector<cv::Point_<int> >&, std::vector<cv::Point_<int> >&)} <conversion>
    while (__comp(__pivot, *__last))
                                  ^
/usr/include/c++/4.8/bits/stl_algo.h:2266:34: note:   candidate expects 3 arguments, 3 provided
In file included from detector_2d.cpp:323:0:
detect_2d.hpp:284:91: note: Detector2D::detect(singleeyefitter::Detector2DProperties&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect&, bool, bool, bool)::__lambda4
  std::sort(split_contours.begin(), split_contours.end(), [](Contour_2D & a, Contour_2D & b) { return a.size() > b.size(); });
                                                                                           ^
detect_2d.hpp:284:91: note:   no known conversion for argument 1 from ‘const std::vector<cv::Point_<int> >’ to ‘singleeyefitter::Contour_2D& {aka std::vector<cv::Point_<int> >&}’
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```


I have a vm of this for you @patrickFuerst .

**Comment by mkassner** [comment]
you also need boost:

```shell
sudo apt-get install libboost-dev
```

**Comment by mkassner** [comment]
I made some fixes and got further now have some remaining problems:

```shell
gcc-4.9 -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/usr/include/python2.7 -c singleeyefitter/EyeModel.cpp -o build/temp.linux-x86_64-2.7/singleeyefitter/EyeModel.o -std=c++11 -w
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/include/x86_64-linux-gnu/c++/4.9/bits/c++allocator.h:33:0,
                 from /usr/include/c++/4.9/bits/allocator.h:46,
                 from /usr/include/c++/4.9/string:41,
                 from /usr/include/c++/4.9/bits/locale_classes.h:40,
                 from /usr/include/c++/4.9/bits/ios_base.h:41,
                 from /usr/include/c++/4.9/ios:42,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/sstream:38,
                 from /usr/include/c++/4.9/complex:45,
                 from /usr/include/eigen3/Eigen/Core:28,
                 from singleeyefitter/common/../Geometry/Ellipse.h:6,
                 from singleeyefitter/common/types.h:5,
                 from singleeyefitter/EyeModel.h:5,
                 from singleeyefitter/EyeModel.cpp:3:
/usr/include/c++/4.9/ext/new_allocator.h: In instantiation of ‘struct __gnu_cxx::new_allocator<const Eigen::ParametrizedLine<double, 2> >’:
/usr/include/c++/4.9/bits/allocator.h:92:11:   required from ‘class std::allocator<const Eigen::ParametrizedLine<double, 2> >’
/usr/include/c++/4.9/bits/alloc_traits.h:85:43:   required from ‘struct std::allocator_traits<std::allocator<const Eigen::ParametrizedLine<double, 2> > >’
/usr/include/c++/4.9/ext/alloc_traits.h:95:10:   required from ‘struct __gnu_cxx::__alloc_traits<std::allocator<const Eigen::ParametrizedLine<double, 2> > >’
/usr/include/c++/4.9/bits/stl_vector.h:75:28:   required from ‘struct std::_Vector_base<const Eigen::ParametrizedLine<double, 2>, std::allocator<const Eigen::ParametrizedLine<double, 2> > >’
/usr/include/c++/4.9/bits/stl_vector.h:214:11:   required from ‘class std::vector<const Eigen::ParametrizedLine<double, 2> >’
singleeyefitter/EyeModel.cpp:163:29:   required from here
/usr/include/c++/4.9/ext/new_allocator.h:93:7: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(__gnu_cxx::new_allocator<_Tp>::const_reference) const [with _Tp = const Eigen::ParametrizedLine<double, 2>; __gnu_cxx::new_allocator<_Tp>::const_pointer = const Eigen::ParametrizedLine<double, 2>*; __gnu_cxx::new_allocator<_Tp>::const_reference = const Eigen::ParametrizedLine<double, 2>&]’ cannot be overloaded
       address(const_reference __x) const _GLIBCXX_NOEXCEPT
       ^
/usr/include/c++/4.9/ext/new_allocator.h:89:7: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(__gnu_cxx::new_allocator<_Tp>::reference) const [with _Tp = const Eigen::ParametrizedLine<double, 2>; __gnu_cxx::new_allocator<_Tp>::pointer = const Eigen::ParametrizedLine<double, 2>*; __gnu_cxx::new_allocator<_Tp>::reference = const Eigen::ParametrizedLine<double, 2>&]’
       address(reference __x) const _GLIBCXX_NOEXCEPT
       ^
/usr/include/c++/4.9/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::deallocate(__gnu_cxx::new_allocator<_Tp>::pointer, __gnu_cxx::new_allocator<_Tp>::size_type) [with _Tp = const Eigen::ParametrizedLine<double, 2>; __gnu_cxx::new_allocator<_Tp>::pointer = const Eigen::ParametrizedLine<double, 2>*; __gnu_cxx::new_allocator<_Tp>::size_type = long unsigned int]’:
/usr/include/c++/4.9/bits/alloc_traits.h:383:9:   required from ‘static void std::allocator_traits<_Alloc>::deallocate(_Alloc&, std::allocator_traits<_Alloc>::pointer, std::allocator_traits<_Alloc>::size_type) [with _Alloc = std::allocator<const Eigen::ParametrizedLine<double, 2> >; std::allocator_traits<_Alloc>::pointer = const Eigen::ParametrizedLine<double, 2>*; std::allocator_traits<_Alloc>::size_type = long unsigned int]’
/usr/include/c++/4.9/bits/stl_vector.h:178:37:   required from ‘void std::_Vector_base<_Tp, _Alloc>::_M_deallocate(std::_Vector_base<_Tp, _Alloc>::pointer, std::size_t) [with _Tp = const Eigen::ParametrizedLine<double, 2>; _Alloc = std::allocator<const Eigen::ParametrizedLine<double, 2> >; std::_Vector_base<_Tp, _Alloc>::pointer = const Eigen::ParametrizedLine<double, 2>*; std::size_t = long unsigned int]’
/usr/include/c++/4.9/bits/stl_vector.h:161:33:   required from ‘std::_Vector_base<_Tp, _Alloc>::~_Vector_base() [with _Tp = const Eigen::ParametrizedLine<double, 2>; _Alloc = std::allocator<const Eigen::ParametrizedLine<double, 2> >]’
/usr/include/c++/4.9/bits/stl_vector.h:257:15:   required from ‘std::vector<_Tp, _Alloc>::vector() [with _Tp = const Eigen::ParametrizedLine<double, 2>; _Alloc = std::allocator<const Eigen::ParametrizedLine<double, 2> >]’
singleeyefitter/EyeModel.cpp:163:29:   required from here
/usr/include/c++/4.9/ext/new_allocator.h:110:30: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
       { ::operator delete(__p); }
                              ^
In file included from /usr/include/c++/4.9/ext/new_allocator.h:33:0,
                 from /usr/include/x86_64-linux-gnu/c++/4.9/bits/c++allocator.h:33,
                 from /usr/include/c++/4.9/bits/allocator.h:46,
                 from /usr/include/c++/4.9/string:41,
                 from /usr/include/c++/4.9/bits/locale_classes.h:40,
                 from /usr/include/c++/4.9/bits/ios_base.h:41,
                 from /usr/include/c++/4.9/ios:42,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/sstream:38,
                 from /usr/include/c++/4.9/complex:45,
                 from /usr/include/eigen3/Eigen/Core:28,
                 from singleeyefitter/common/../Geometry/Ellipse.h:6,
                 from singleeyefitter/common/types.h:5,
                 from singleeyefitter/EyeModel.h:5,
                 from singleeyefitter/EyeModel.cpp:3:
/usr/include/c++/4.9/new:132:6: note: initializing argument 1 of ‘void operator delete(void*)’
 void operator delete(void*) _GLIBCXX_USE_NOEXCEPT
      ^
In file included from /usr/include/c++/4.9/bits/stl_tempbuf.h:60:0,
                 from /usr/include/c++/4.9/bits/stl_algo.h:62,
                 from /usr/include/c++/4.9/algorithm:62,
                 from /usr/include/eigen3/Eigen/Core:160,
                 from singleeyefitter/common/../Geometry/Ellipse.h:6,
                 from singleeyefitter/common/types.h:5,
                 from singleeyefitter/EyeModel.h:5,
                 from singleeyefitter/EyeModel.cpp:3:
/usr/include/c++/4.9/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = const Eigen::ParametrizedLine<double, 2>; _Args = {const Eigen::ParametrizedLine<double, 2, 0>&}]’:
/usr/include/c++/4.9/bits/stl_uninitialized.h:75:53:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const Eigen::ParametrizedLine<double, 2>*; _ForwardIterator = const Eigen::ParametrizedLine<double, 2>*; bool _TrivialValueTypes = false]’
/usr/include/c++/4.9/bits/stl_uninitialized.h:126:41:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const Eigen::ParametrizedLine<double, 2>*; _ForwardIterator = const Eigen::ParametrizedLine<double, 2>*]’
/usr/include/c++/4.9/bits/stl_uninitialized.h:279:63:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = const Eigen::ParametrizedLine<double, 2>*; _ForwardIterator = const Eigen::ParametrizedLine<double, 2>*; _Tp = const Eigen::ParametrizedLine<double, 2>]’
/usr/include/c++/4.9/bits/stl_uninitialized.h:302:69:   required from ‘_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = const Eigen::ParametrizedLine<double, 2>*; _ForwardIterator = const Eigen::ParametrizedLine<double, 2>*; _Allocator = std::allocator<const Eigen::ParametrizedLine<double, 2> >]’
/usr/include/c++/4.9/bits/vector.tcc:423:43:   required from ‘void std::vector<_Tp, _Alloc>::_M_emplace_back_aux(_Args&& ...) [with _Args = {const Eigen::ParametrizedLine<double, 2, 0>&}; _Tp = const Eigen::ParametrizedLine<double, 2>; _Alloc = std::allocator<const Eigen::ParametrizedLine<double, 2> >]’
/usr/include/c++/4.9/bits/stl_vector.h:923:27:   required from ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = const Eigen::ParametrizedLine<double, 2>; _Alloc = std::allocator<const Eigen::ParametrizedLine<double, 2> >; std::vector<_Tp, _Alloc>::value_type = const Eigen::ParametrizedLine<double, 2>]’
singleeyefitter/EyeModel.cpp:165:92:   required from here
/usr/include/c++/4.9/bits/stl_construct.h:75:7: error: invalid static_cast from type ‘const Eigen::ParametrizedLine<double, 2>*’ to type ‘void*’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^
error: command 'gcc-4.9' failed with exit status 1
```

**Comment by mkassner** [comment]
For the above I believe I was using gcc-4.9 

```shell
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-4.9
```

**Comment by patrickFuerst** [comment]
Resolved compile error with  0fbe69a066f1d8d44fdf854499c034d3d20ade47. 
Working with gcc-4.9. 

In order to fully work, ceres needs to be build as a dynamic library: 
Adapted ceres instructions are: 
````
tar zxf ceres-solver-1.11.0.tar.gz
cd ceres
mkdir build && cd build
cmake .. -DBUILD_SHARED_LIBS=ON 
make -j3
make test
sudo make install
```
Further ceres doesn't get installed to `/usr/lib` rather than `/usr/local/lib`, thus the dynamic linker needs to know where to find it. 

There are several way but I would recommend going with ldconfig. 
Steps for this: 
   1.  Create a new file in `/ect/ld.so.conf.d` with sudo called `ceres.conf` 
   2.  Add the line  `/usr/local/lib`
   3.  run `ldconfig` to update the cache

This way everything from opencv to avutils is located in `/usr/local/lib`

**Comment by cpicanco** [comment]
May be useful:
http://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-4-9-on-ubuntu-14-04

**Comment by mkassner** [comment]
concerning ldcong:

```shell
sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/ceres.conf'
sudo ldconfig
```

**Comment by mkassner** [comment]
ok. This is done. I ll update the setup doctumentation for linux and then close this issue.

**Comment by mkassner** [comment]
before I forget:

ceres needs to be build with:

```shell
cmake .. -DBUILD_SHARED_LIBS=ON
```

**Comment by cpicanco** [comment]
yes, Patrick already noted this

**Comment by mkassner** [comment]
no need for gcc-4.9 anymore.

**Comment by mkassner** [comment]
This now also bundles and is portable to other machines running 14.04.
